#ifndef FONT_PHOSPHOR_H
#define FONT_PHOSPHOR_H

/*
 * Phosphor UI 图标字体宏（2026-04-30 接管 FA 6 Free 中的 UI 图标子集）
 *
 * 字体源：./ttf/Phosphor-Fill.ttf  (≥20px)
 *         ./ttf/Phosphor-Regular.ttf (≤16px)
 * LVGL 字体符号：font_phosphor_14_1 / font_phosphor_16_4 / font_phosphor_20_4 / font_phosphor_30_4
 * fallback 链：font_phosphor_X_Y -> font_awesome_X_Y（emoji 子集）
 *
 * 业务调用：保持 FONT_AWESOME_WIFI / SIGNAL_* / BATTERY_* / VOLUME_* 等宏，
 *          实际展开为 Phosphor codepoint（见末尾 alias 段）。
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>

typedef struct {
    const char* name;
    const char* utf8_string;
} font_phosphor_symbol_t;

#define FONT_PHOSPHOR_BATTERY_FULL "\xee\x83\x80"
#define FONT_PHOSPHOR_BATTERY_THREE_QUARTERS "\xee\x83\x82"
#define FONT_PHOSPHOR_BATTERY_HALF "\xee\x83\x86"
#define FONT_PHOSPHOR_BATTERY_QUARTER "\xee\x83\x84"
#define FONT_PHOSPHOR_BATTERY_EMPTY "\xee\x82\xbe"
#define FONT_PHOSPHOR_BATTERY_SLASH "\xee\x83\x88"
#define FONT_PHOSPHOR_BATTERY_BOLT "\xee\x82\xba"
#define FONT_PHOSPHOR_WIFI "\xee\x93\xaa"
#define FONT_PHOSPHOR_WIFI_FAIR "\xee\x93\xae"
#define FONT_PHOSPHOR_WIFI_WEAK "\xee\x93\xac"
#define FONT_PHOSPHOR_WIFI_SLASH "\xee\x93\xb2"
#define FONT_PHOSPHOR_SIGNAL "\xee\x85\x82"
#define FONT_PHOSPHOR_SIGNAL_STRONG "\xee\x85\x82"
#define FONT_PHOSPHOR_SIGNAL_GOOD "\xee\x85\x84"
#define FONT_PHOSPHOR_SIGNAL_FAIR "\xee\x85\x88"
#define FONT_PHOSPHOR_SIGNAL_WEAK "\xee\x85\x86"
#define FONT_PHOSPHOR_SIGNAL_OFF "\xee\x85\x8c"
#define FONT_PHOSPHOR_VOLUME_HIGH "\xee\x91\x8a"
#define FONT_PHOSPHOR_VOLUME "\xee\x91\x8c"
#define FONT_PHOSPHOR_VOLUME_LOW "\xee\x91\x8c"
#define FONT_PHOSPHOR_VOLUME_XMARK "\xee\x91\x9c"
#define FONT_PHOSPHOR_MUSIC "\xee\x8c\xbc"
#define FONT_PHOSPHOR_PLAY "\xee\x8f\x90"
#define FONT_PHOSPHOR_PAUSE "\xee\x8e\x9e"
#define FONT_PHOSPHOR_STOP "\xee\x91\xac"
#define FONT_PHOSPHOR_BACKWARD_STEP "\xee\x96\xa4"
#define FONT_PHOSPHOR_FORWARD_STEP "\xee\x96\xa6"
#define FONT_PHOSPHOR_CHECK "\xee\x86\x82"
#define FONT_PHOSPHOR_XMARK "\xee\x93\xb6"
#define FONT_PHOSPHOR_POWER_OFF "\xee\x8f\x9a"
#define FONT_PHOSPHOR_GEAR "\xee\x89\xb0"
#define FONT_PHOSPHOR_TRASH "\xee\x92\xa6"
#define FONT_PHOSPHOR_HOUSE "\xee\x8b\x82"
#define FONT_PHOSPHOR_IMAGE "\xee\x8b\x8a"
#define FONT_PHOSPHOR_PEN_TO_SQUARE "\xee\xaf\x86"
#define FONT_PHOSPHOR_COMMENT "\xee\x85\xa8"
#define FONT_PHOSPHOR_COMMENT_QUESTION "\xee\x85\xae"
#define FONT_PHOSPHOR_ARROW_LEFT "\xee\x81\x98"
#define FONT_PHOSPHOR_ARROW_RIGHT "\xee\x81\xac"
#define FONT_PHOSPHOR_ARROW_UP "\xee\x82\x8e"
#define FONT_PHOSPHOR_ARROW_DOWN "\xee\x80\xbe"
#define FONT_PHOSPHOR_ANGLE_LEFT "\xee\x84\xb8"
#define FONT_PHOSPHOR_ANGLE_RIGHT "\xee\x84\xba"
#define FONT_PHOSPHOR_ANGLE_UP "\xee\x84\xbc"
#define FONT_PHOSPHOR_ANGLE_DOWN "\xee\x84\xb6"
#define FONT_PHOSPHOR_ANGLES_LEFT "\xee\x84\xa8"
#define FONT_PHOSPHOR_ANGLES_RIGHT "\xee\x84\xaa"
#define FONT_PHOSPHOR_ANGLES_UP "\xee\x84\xac"
#define FONT_PHOSPHOR_ANGLES_DOWN "\xee\x84\xa6"
#define FONT_PHOSPHOR_ARROWS_REPEAT "\xee\x82\x94"
#define FONT_PHOSPHOR_ARROWS_ROTATE "\xee\x82\x96"
#define FONT_PHOSPHOR_CLOUD_ARROW_DOWN "\xee\x86\xac"
#define FONT_PHOSPHOR_CLOUD_ARROW_UP "\xee\x86\xae"
#define FONT_PHOSPHOR_CLOUD_SLASH "\xee\xaa\x96"
#define FONT_PHOSPHOR_SUN "\xee\x91\xb2"
#define FONT_PHOSPHOR_MOON "\xee\x8c\xb0"
#define FONT_PHOSPHOR_CLOUD "\xee\x86\xaa"
#define FONT_PHOSPHOR_CLOUDS "\xee\x86\xaa"
#define FONT_PHOSPHOR_CLOUD_SUN "\xee\x95\x80"
#define FONT_PHOSPHOR_CLOUD_SUN_RAIN "\xee\x86\xb4"
#define FONT_PHOSPHOR_CLOUD_MOON "\xee\x94\xbe"
#define FONT_PHOSPHOR_CLOUD_BOLT "\xee\x86\xb2"
#define FONT_PHOSPHOR_CLOUD_HAIL "\xee\x86\xb8"
#define FONT_PHOSPHOR_CLOUD_SLEET "\xee\x86\xb8"
#define FONT_PHOSPHOR_CLOUD_DRIZZLE "\xee\x86\xb4"
#define FONT_PHOSPHOR_CLOUD_FOG "\xee\x94\xbc"
#define FONT_PHOSPHOR_CLOUD_RAIN "\xee\x86\xb4"
#define FONT_PHOSPHOR_CLOUD_SHOWERS "\xee\x86\xb4"
#define FONT_PHOSPHOR_CLOUD_SHOWERS_HEAVY "\xee\x86\xb4"
#define FONT_PHOSPHOR_SNOWFLAKE "\xee\x96\xaa"
#define FONT_PHOSPHOR_SNOWFLAKES "\xee\x96\xaa"
#define FONT_PHOSPHOR_SMOG "\xee\x94\xbc"
#define FONT_PHOSPHOR_WIND "\xee\x97\x92"
#define FONT_PHOSPHOR_HURRICANE "\xee\xa7\xba"
#define FONT_PHOSPHOR_TORNADO "\xee\xa2\x8c"
#define FONT_PHOSPHOR_TRIANGLE_EXCLAMATION "\xee\x93\xa0"
#define FONT_PHOSPHOR_BELL "\xee\x83\x8e"
#define FONT_PHOSPHOR_LOCATION_DOT "\xee\x8c\x96"
#define FONT_PHOSPHOR_GLOBE "\xee\x8a\x88"
#define FONT_PHOSPHOR_LOCATION_ARROW "\xee\xab\x9e"
#define FONT_PHOSPHOR_SD_CARD "\xee\x99\xa4"
#define FONT_PHOSPHOR_BLUETOOTH "\xee\x83\x9a"
#define FONT_PHOSPHOR_MICROCHIP_AI "\xee\x98\x90"
#define FONT_PHOSPHOR_GPS "\xee\xb7\x98"
#define FONT_PHOSPHOR_GPS_FIX "\xee\xb7\x96"
#define FONT_PHOSPHOR_GPS_SLASH "\xee\xb7\x94"
#define FONT_PHOSPHOR_BLUETOOTH_CONNECTED "\xee\x83\x9c"
#define FONT_PHOSPHOR_BLUETOOTH_SLASH "\xee\x83\x9e"
#define FONT_PHOSPHOR_BLUETOOTH_X "\xee\x83\xa0"
#define FONT_PHOSPHOR_BROADCAST "\xee\x83\xb2"
#define FONT_PHOSPHOR_NFC "\xee\x83\xb2"
#define FONT_PHOSPHOR_IBEACON "\xee\x83\xb2"
#define FONT_PHOSPHOR_CELL_TOWER "\xee\xae\xaa"
#define FONT_PHOSPHOR_USER "\xee\x93\x82"
#define FONT_PHOSPHOR_USER_ROBOT "\xee\x9d\xa2"
#define FONT_PHOSPHOR_DOWNLOAD "\xee\x88\x8c"
#define FONT_PHOSPHOR_LOCK "\xee\x8b\xba"
#define FONT_PHOSPHOR_UNLOCK "\xee\x8c\x86"
#define FONT_PHOSPHOR_KEY "\xee\x8b\x96"
#define FONT_PHOSPHOR_LINK "\xee\x8b\xa2"
#define FONT_PHOSPHOR_CIRCLE_INFO "\xee\x8b\x8e"
#define FONT_PHOSPHOR_CIRCLE_QUESTION "\xee\x8f\xa8"
#define FONT_PHOSPHOR_CIRCLE_CHECK "\xee\x86\x84"
#define FONT_PHOSPHOR_CIRCLE_XMARK "\xee\x93\xb8"
#define FONT_PHOSPHOR_CLOCK "\xee\x86\x9a"
#define FONT_PHOSPHOR_ALARM_CLOCK "\xee\x80\x86"
#define FONT_PHOSPHOR_SPINNER "\xee\xad\x84"
#define FONT_PHOSPHOR_TEMPERATURE_HALF "\xee\x97\x8c"
#define FONT_PHOSPHOR_HEADPHONES "\xee\x8a\xa6"
#define FONT_PHOSPHOR_MICROPHONE "\xee\x8c\xa6"
#define FONT_PHOSPHOR_MICROPHONE_SLASH "\xee\x8c\xa8"
#define FONT_PHOSPHOR_CAMERA "\xee\x84\x8e"
#define FONT_PHOSPHOR_CALENDAR "\xee\x84\x88"
#define FONT_PHOSPHOR_ENVELOPE "\xee\x88\x94"
#define FONT_PHOSPHOR_BRIGHTNESS "\xee\x91\xb4"
#define FONT_PHOSPHOR_PHONE "\xee\x8e\xb8"
#define FONT_PHOSPHOR_COMPASS "\xee\x87\x88"
#define FONT_PHOSPHOR_CALCULATOR "\xee\x94\xb8"
#define FONT_PHOSPHOR_GLASSES "\xee\x9e\xba"
#define FONT_PHOSPHOR_MAGNIFYING_GLASS "\xee\x8c\x8c"
#define FONT_PHOSPHOR_HEART "\xee\x8a\xa8"
#define FONT_PHOSPHOR_STAR "\xee\x91\xaa"
#define FONT_PHOSPHOR_GAMEPAD "\xee\x89\xae"
#define FONT_PHOSPHOR_WATCH "\xee\x93\xa6"

// FA 兼容 alias —— 业务调用点 FONT_AWESOME_WIFI 等沿用旧名，实际渲染 Phosphor 字形
#define FONT_AWESOME_BATTERY_FULL FONT_PHOSPHOR_BATTERY_FULL
#define FONT_AWESOME_BATTERY_THREE_QUARTERS FONT_PHOSPHOR_BATTERY_THREE_QUARTERS
#define FONT_AWESOME_BATTERY_HALF FONT_PHOSPHOR_BATTERY_HALF
#define FONT_AWESOME_BATTERY_QUARTER FONT_PHOSPHOR_BATTERY_QUARTER
#define FONT_AWESOME_BATTERY_EMPTY FONT_PHOSPHOR_BATTERY_EMPTY
#define FONT_AWESOME_BATTERY_SLASH FONT_PHOSPHOR_BATTERY_SLASH
#define FONT_AWESOME_BATTERY_BOLT FONT_PHOSPHOR_BATTERY_BOLT
#define FONT_AWESOME_WIFI FONT_PHOSPHOR_WIFI
#define FONT_AWESOME_WIFI_FAIR FONT_PHOSPHOR_WIFI_FAIR
#define FONT_AWESOME_WIFI_WEAK FONT_PHOSPHOR_WIFI_WEAK
#define FONT_AWESOME_WIFI_SLASH FONT_PHOSPHOR_WIFI_SLASH
#define FONT_AWESOME_SIGNAL FONT_PHOSPHOR_SIGNAL
#define FONT_AWESOME_SIGNAL_STRONG FONT_PHOSPHOR_SIGNAL_STRONG
#define FONT_AWESOME_SIGNAL_GOOD FONT_PHOSPHOR_SIGNAL_GOOD
#define FONT_AWESOME_SIGNAL_FAIR FONT_PHOSPHOR_SIGNAL_FAIR
#define FONT_AWESOME_SIGNAL_WEAK FONT_PHOSPHOR_SIGNAL_WEAK
#define FONT_AWESOME_SIGNAL_OFF FONT_PHOSPHOR_SIGNAL_OFF
#define FONT_AWESOME_VOLUME_HIGH FONT_PHOSPHOR_VOLUME_HIGH
#define FONT_AWESOME_VOLUME FONT_PHOSPHOR_VOLUME
#define FONT_AWESOME_VOLUME_LOW FONT_PHOSPHOR_VOLUME_LOW
#define FONT_AWESOME_VOLUME_XMARK FONT_PHOSPHOR_VOLUME_XMARK
#define FONT_AWESOME_MUSIC FONT_PHOSPHOR_MUSIC
#define FONT_AWESOME_PLAY FONT_PHOSPHOR_PLAY
#define FONT_AWESOME_PAUSE FONT_PHOSPHOR_PAUSE
#define FONT_AWESOME_STOP FONT_PHOSPHOR_STOP
#define FONT_AWESOME_BACKWARD_STEP FONT_PHOSPHOR_BACKWARD_STEP
#define FONT_AWESOME_FORWARD_STEP FONT_PHOSPHOR_FORWARD_STEP
#define FONT_AWESOME_CHECK FONT_PHOSPHOR_CHECK
#define FONT_AWESOME_XMARK FONT_PHOSPHOR_XMARK
#define FONT_AWESOME_POWER_OFF FONT_PHOSPHOR_POWER_OFF
#define FONT_AWESOME_GEAR FONT_PHOSPHOR_GEAR
#define FONT_AWESOME_TRASH FONT_PHOSPHOR_TRASH
#define FONT_AWESOME_HOUSE FONT_PHOSPHOR_HOUSE
#define FONT_AWESOME_IMAGE FONT_PHOSPHOR_IMAGE
#define FONT_AWESOME_PEN_TO_SQUARE FONT_PHOSPHOR_PEN_TO_SQUARE
#define FONT_AWESOME_COMMENT FONT_PHOSPHOR_COMMENT
#define FONT_AWESOME_COMMENT_QUESTION FONT_PHOSPHOR_COMMENT_QUESTION
#define FONT_AWESOME_ARROW_LEFT FONT_PHOSPHOR_ARROW_LEFT
#define FONT_AWESOME_ARROW_RIGHT FONT_PHOSPHOR_ARROW_RIGHT
#define FONT_AWESOME_ARROW_UP FONT_PHOSPHOR_ARROW_UP
#define FONT_AWESOME_ARROW_DOWN FONT_PHOSPHOR_ARROW_DOWN
#define FONT_AWESOME_ANGLE_LEFT FONT_PHOSPHOR_ANGLE_LEFT
#define FONT_AWESOME_ANGLE_RIGHT FONT_PHOSPHOR_ANGLE_RIGHT
#define FONT_AWESOME_ANGLE_UP FONT_PHOSPHOR_ANGLE_UP
#define FONT_AWESOME_ANGLE_DOWN FONT_PHOSPHOR_ANGLE_DOWN
#define FONT_AWESOME_ANGLES_LEFT FONT_PHOSPHOR_ANGLES_LEFT
#define FONT_AWESOME_ANGLES_RIGHT FONT_PHOSPHOR_ANGLES_RIGHT
#define FONT_AWESOME_ANGLES_UP FONT_PHOSPHOR_ANGLES_UP
#define FONT_AWESOME_ANGLES_DOWN FONT_PHOSPHOR_ANGLES_DOWN
#define FONT_AWESOME_ARROWS_REPEAT FONT_PHOSPHOR_ARROWS_REPEAT
#define FONT_AWESOME_ARROWS_ROTATE FONT_PHOSPHOR_ARROWS_ROTATE
#define FONT_AWESOME_CLOUD_ARROW_DOWN FONT_PHOSPHOR_CLOUD_ARROW_DOWN
#define FONT_AWESOME_CLOUD_ARROW_UP FONT_PHOSPHOR_CLOUD_ARROW_UP
#define FONT_AWESOME_CLOUD_SLASH FONT_PHOSPHOR_CLOUD_SLASH
#define FONT_AWESOME_SUN FONT_PHOSPHOR_SUN
#define FONT_AWESOME_MOON FONT_PHOSPHOR_MOON
#define FONT_AWESOME_CLOUD FONT_PHOSPHOR_CLOUD
#define FONT_AWESOME_CLOUDS FONT_PHOSPHOR_CLOUDS
#define FONT_AWESOME_CLOUD_SUN FONT_PHOSPHOR_CLOUD_SUN
#define FONT_AWESOME_CLOUD_SUN_RAIN FONT_PHOSPHOR_CLOUD_SUN_RAIN
#define FONT_AWESOME_CLOUD_MOON FONT_PHOSPHOR_CLOUD_MOON
#define FONT_AWESOME_CLOUD_BOLT FONT_PHOSPHOR_CLOUD_BOLT
#define FONT_AWESOME_CLOUD_HAIL FONT_PHOSPHOR_CLOUD_HAIL
#define FONT_AWESOME_CLOUD_SLEET FONT_PHOSPHOR_CLOUD_SLEET
#define FONT_AWESOME_CLOUD_DRIZZLE FONT_PHOSPHOR_CLOUD_DRIZZLE
#define FONT_AWESOME_CLOUD_FOG FONT_PHOSPHOR_CLOUD_FOG
#define FONT_AWESOME_CLOUD_RAIN FONT_PHOSPHOR_CLOUD_RAIN
#define FONT_AWESOME_CLOUD_SHOWERS FONT_PHOSPHOR_CLOUD_SHOWERS
#define FONT_AWESOME_CLOUD_SHOWERS_HEAVY FONT_PHOSPHOR_CLOUD_SHOWERS_HEAVY
#define FONT_AWESOME_SNOWFLAKE FONT_PHOSPHOR_SNOWFLAKE
#define FONT_AWESOME_SNOWFLAKES FONT_PHOSPHOR_SNOWFLAKES
#define FONT_AWESOME_SMOG FONT_PHOSPHOR_SMOG
#define FONT_AWESOME_WIND FONT_PHOSPHOR_WIND
#define FONT_AWESOME_HURRICANE FONT_PHOSPHOR_HURRICANE
#define FONT_AWESOME_TORNADO FONT_PHOSPHOR_TORNADO
#define FONT_AWESOME_TRIANGLE_EXCLAMATION FONT_PHOSPHOR_TRIANGLE_EXCLAMATION
#define FONT_AWESOME_BELL FONT_PHOSPHOR_BELL
#define FONT_AWESOME_LOCATION_DOT FONT_PHOSPHOR_LOCATION_DOT
#define FONT_AWESOME_GLOBE FONT_PHOSPHOR_GLOBE
#define FONT_AWESOME_LOCATION_ARROW FONT_PHOSPHOR_LOCATION_ARROW
#define FONT_AWESOME_SD_CARD FONT_PHOSPHOR_SD_CARD
#define FONT_AWESOME_BLUETOOTH FONT_PHOSPHOR_BLUETOOTH
#define FONT_AWESOME_MICROCHIP_AI FONT_PHOSPHOR_MICROCHIP_AI
#define FONT_AWESOME_GPS FONT_PHOSPHOR_GPS
#define FONT_AWESOME_GPS_FIX FONT_PHOSPHOR_GPS_FIX
#define FONT_AWESOME_GPS_SLASH FONT_PHOSPHOR_GPS_SLASH
#define FONT_AWESOME_BLUETOOTH_CONNECTED FONT_PHOSPHOR_BLUETOOTH_CONNECTED
#define FONT_AWESOME_BLUETOOTH_SLASH FONT_PHOSPHOR_BLUETOOTH_SLASH
#define FONT_AWESOME_BLUETOOTH_X FONT_PHOSPHOR_BLUETOOTH_X
#define FONT_AWESOME_BROADCAST FONT_PHOSPHOR_BROADCAST
#define FONT_AWESOME_NFC FONT_PHOSPHOR_NFC
#define FONT_AWESOME_IBEACON FONT_PHOSPHOR_IBEACON
#define FONT_AWESOME_CELL_TOWER FONT_PHOSPHOR_CELL_TOWER
#define FONT_AWESOME_USER FONT_PHOSPHOR_USER
#define FONT_AWESOME_USER_ROBOT FONT_PHOSPHOR_USER_ROBOT
#define FONT_AWESOME_DOWNLOAD FONT_PHOSPHOR_DOWNLOAD
#define FONT_AWESOME_LOCK FONT_PHOSPHOR_LOCK
#define FONT_AWESOME_UNLOCK FONT_PHOSPHOR_UNLOCK
#define FONT_AWESOME_KEY FONT_PHOSPHOR_KEY
#define FONT_AWESOME_LINK FONT_PHOSPHOR_LINK
#define FONT_AWESOME_CIRCLE_INFO FONT_PHOSPHOR_CIRCLE_INFO
#define FONT_AWESOME_CIRCLE_QUESTION FONT_PHOSPHOR_CIRCLE_QUESTION
#define FONT_AWESOME_CIRCLE_CHECK FONT_PHOSPHOR_CIRCLE_CHECK
#define FONT_AWESOME_CIRCLE_XMARK FONT_PHOSPHOR_CIRCLE_XMARK
#define FONT_AWESOME_CLOCK FONT_PHOSPHOR_CLOCK
#define FONT_AWESOME_ALARM_CLOCK FONT_PHOSPHOR_ALARM_CLOCK
#define FONT_AWESOME_SPINNER FONT_PHOSPHOR_SPINNER
#define FONT_AWESOME_TEMPERATURE_HALF FONT_PHOSPHOR_TEMPERATURE_HALF
#define FONT_AWESOME_HEADPHONES FONT_PHOSPHOR_HEADPHONES
#define FONT_AWESOME_MICROPHONE FONT_PHOSPHOR_MICROPHONE
#define FONT_AWESOME_MICROPHONE_SLASH FONT_PHOSPHOR_MICROPHONE_SLASH
#define FONT_AWESOME_CAMERA FONT_PHOSPHOR_CAMERA
#define FONT_AWESOME_CALENDAR FONT_PHOSPHOR_CALENDAR
#define FONT_AWESOME_ENVELOPE FONT_PHOSPHOR_ENVELOPE
#define FONT_AWESOME_BRIGHTNESS FONT_PHOSPHOR_BRIGHTNESS
#define FONT_AWESOME_PHONE FONT_PHOSPHOR_PHONE
#define FONT_AWESOME_COMPASS FONT_PHOSPHOR_COMPASS
#define FONT_AWESOME_CALCULATOR FONT_PHOSPHOR_CALCULATOR
#define FONT_AWESOME_GLASSES FONT_PHOSPHOR_GLASSES
#define FONT_AWESOME_MAGNIFYING_GLASS FONT_PHOSPHOR_MAGNIFYING_GLASS
#define FONT_AWESOME_HEART FONT_PHOSPHOR_HEART
#define FONT_AWESOME_STAR FONT_PHOSPHOR_STAR
#define FONT_AWESOME_GAMEPAD FONT_PHOSPHOR_GAMEPAD
#define FONT_AWESOME_WATCH FONT_PHOSPHOR_WATCH

extern const font_phosphor_symbol_t font_phosphor_symbols[];
extern const size_t font_phosphor_symbol_count;

static inline const char* font_phosphor_get_utf8(const char* name) {
    if (!name) return NULL;
    for (size_t i = 0; i < font_phosphor_symbol_count; i++) {
        if (strcmp(font_phosphor_symbols[i].name, name) == 0) {
            return font_phosphor_symbols[i].utf8_string;
        }
    }
    return NULL;
}

#endif
